### PR TITLE
Update super() method usage

### PR DESCRIPTION
**Pull request by muraty**
Python 2.7 doesn't support this syntax. super() should have arguments in Python 2

### CODE REVIEW

**Comment by macro1** [comment]
Hi @muraty! The latest version of the workshop has actually be updated to the Python 3 syntax. If you would like to go through it in Python 2.7, it might be easier to use an older version that was still written for that version: http://test-driven-django-development.readthedocs.org/en/v2.0/

**Comment by willingc** [comment]
@muraty Thanks for the pull request. Currently, the prerequisites for the tutorial are Python 3 (http://test-driven-django-development.readthedocs.org/en/latest/#prerequisites). For teaching workshops, we concluded that Python 3 met the needs of our attendees.

Team, it might make sense to have a doc page that has miscellaneous (though unsupported by us) Python 2 tutorial changes like the one suggested by @muraty. Also, we should update the readme to list the tutorial prerequisites.

I'm closing this pull request. Thanks again @muraty.

**Comment by muraty** [comment]
That's my fault, then. AFAIR, I haven't seen python version for the tutorial. Thanks for your quick reply!

**Comment by willingc** [comment]
@muraty You are very welcome. Thanks for bringing up your question since it is prompting us to update our readme to make it more clear which versions that the tutorial supports. :cake:

You may enjoy Harry Percival's TDD work too http://chimera.labs.oreilly.com/books/1234000000754/index.html

**Pull request closed without merging**
